#!/bin/sh

set -ex

# Fetch all commits/refs needed to run our tests.
git fetch origin master:master v2.0.0:v2.0.0 test/attributes:test/attributes test/master:test/master

git submodule init
git submodule sync --quiet
script/fast-submodule-update
